# Generated by Django 4.2.16 on 2026-05-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_intersectionwaitevent_activewaiter'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activewaiter',
            new_name='analytics_a_grid_id_33c7a9_idx',
            old_name='analytics_a_grid_id_b7c2d1_idx',
        ),
        migrations.RenameIndex(
            model_name='intersectionwaitevent',
            new_name='analytics_i_grid_id_fe8c50_idx',
            old_name='analytics_i_grid_id_e3a8f4_idx',
        ),
    ]
